# Generated by Django 4.2.8 on 2023-12-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagement', '0002_contact_delete_createcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.CharField(default='No notes', max_length=255),
        ),
    ]
