# Generated by Django 4.2.8 on 2023-12-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagement', '0003_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
